import { readable } from "svelte/store";
export let recipes = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    image: "paneer-butter-masala.jpg",
    tagline:
      "Indulge in Creamy Delight, Paneer Perfected in Rich Tomato Bliss!",
    ingredients: [
      "250 grams paneer, cubed",
      "3 large tomatoes, chopped",
      "2 onions, finely chopped",
      "2-3 cloves of garlic, minced",
      "1-inch ginger, grated",
      "1 green chili, finely chopped (optional)",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon coriander powder",
      "1/2 teaspoon turmeric powder",
      "1/2 cup cream",
      "2 tablespoons butter",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for garnish",
    ],
    instructions: [
      "Heat oil in a pan, add chopped onions, garlic, and ginger. Sauté until onions turn translucent.",
      "Add chopped tomatoes and cook until they turn mushy.",
      "Allow the mixture to cool, then blend it into a smooth paste.",
      "Heat butter in a pan, add the tomato-onion paste, red chili powder, coriander powder, turmeric powder, and salt. Cook for 5-7 minutes.",
      "Add paneer cubes and cook for another 2-3 minutes.",
      "Pour in cream and simmer for a few minutes until the curry thickens.",
      "Garnish with fresh coriander leaves and serve hot with naan or rice.",
    ],
  },
  {
    id: 2,
    name: "Paneer Tikka",
    image: "paneer-tikka-masala.jpg",
    tagline: "Sizzling Skewers of Spice and Succulence – Paneer Tikka Magic!",
    ingredients: [
      "250 grams paneer, cubed",
      "1 bell pepper, diced",
      "1 onion, diced",
      "1 cup thick yogurt",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon turmeric powder",
      "2 tablespoons lemon juice",
      "Salt to taste",
      "2 tablespoons oil",
      "Skewers for grilling",
    ],
    instructions: [
      "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, garam masala, cumin powder, coriander powder, turmeric powder, lemon juice, and salt to form a marinade.",
      "Add paneer cubes, diced bell pepper, and onion to the marinade. Coat them well and let it marinate for at least 1-2 hours in the refrigerator.",
      "Preheat the grill or oven to medium-high heat.",
      "Skewer the marinated paneer, bell pepper, and onion alternately onto skewers.",
      "Brush the skewered paneer and vegetables with oil and grill for 10-12 minutes, turning occasionally until they are slightly charred.",
      "Serve hot with mint chutney and onion rings.",
    ],
  },
  {
    id: 3,
    name: "Palak Paneer",
    image: "palak-paneer.jpg",
    tagline:
      "A Wholesome Green Symphony, Where Spinach Embraces Paneer's Charm!",
    ingredients: [
      "250 grams paneer, cubed",
      "2 bunches of spinach, washed and chopped",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 green chilies, chopped (adjust to spice preference)",
      "1-inch ginger, grated",
      "4-5 cloves of garlic, minced",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric powder",
      "1/2 cup cream",
      "2 tablespoons oil or ghee",
      "Salt to taste",
    ],
    instructions: [
      "Blanch the spinach in boiling water for 2-3 minutes. Drain and transfer to ice-cold water. Blend it into a smooth puree.",
      "Heat oil in a pan, add cumin seeds. Once they splutter, add chopped onions, garlic, ginger, and green chilies. Sauté until onions turn golden brown.",
      "Add chopped tomatoes, turmeric powder, garam masala, and salt. Cook until tomatoes are soft and oil starts separating.",
      "Pour in the spinach puree and cook for 5-7 minutes on medium heat.",
      "Add paneer cubes and cook for another 2-3 minutes.",
      "Finally, add cream, stir well, and cook for a couple of minutes until everything is blended well.",
      "Serve hot with naan or rice.",
    ],
  },
];
